DROP TABLE IF EXISTS Plant;
DROP TABLE IF EXISTS Schedule;
DROP TABLE IF EXISTS Log;

CREATE TABLE Plant(
	id INT PRIMARY KEY,
	species VARCHAR(50),
	--FOREIGN KEY (schedule) REFERENCES Schedule
	schedule INT,
	FOREIGN KEY (schedule) REFERENCES Schedule
);

CREATE TABLE Schedule(
	interval INT PRIMARY KEY
);

CREATE TABLE Log(
	id INT,
	day VARCHAR(20),
	PRIMARY KEY (id, day),
	FOREIGN KEY (id) REFERENCES Plant
);